# Generated by Django 5.1.5 on 2025-01-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role_vacancies',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
