# Generated by Django 5.1.6 on 2025-02-07 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_notification_extra_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application', 'Project Application'), ('like', 'Project Like'), ('comment', 'Project Comment'), ('application_accepted', 'Application Accepted'), ('application_rejected', 'Application Rejected'), ('team_update', 'Team Update'), ('project_update', 'Project Update'), ('system', 'System Notification'), ('new_follower', 'New Follower'), ('followed_new_project', 'Followed User New Project'), ('followed_joined_project', 'Followed User Joined Project')], max_length=50),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
