# Generated by Django 5.1.6 on 2025-02-07 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_notification_notification_type_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application', 'Project Application'), ('like', 'Project Like'), ('comment', 'Project Comment'), ('application_accepted', 'Application Accepted'), ('application_rejected', 'Application Rejected'), ('team_update', 'Team Update'), ('project_update', 'Project Update'), ('system', 'System Notification'), ('connection_request', 'Connection Request'), ('connection_accepted', 'Connection Accepted'), ('connection_rejected', 'Connection Rejected'), ('connected_new_project', 'Connection New Project'), ('connected_joined_project', 'Connection Joined Project')], max_length=50),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('requester', 'receiver')},
            },
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
